version: '3.8'

services:
  orientdb:
    image: orientdb:latest
    container_name: dbcli
    restart: unless-stopped
    command: server.sh -Ddistributed=false -Dstorage.useWAL=false -XX:+PerfDisableSharedMem -Dstorage.wal.syncOnPageFlush=false -Dtx.useLog=false -XX:MaxDirectMemorySize=8192M -Dstorage.diskCache.bufferSize=8192
    ports:
      - "127.0.0.1:2424:2424"
      - "127.0.0.1:2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
      ORIENTDB_USERNAME: admin
      ORIENTDB_PASSWORD: adminpwd
      ORIENTDB_DATABASE: dbcli
      ORIENTDB_OPTS_MEMORY: "-Xms1G -Xmx10G"
    volumes:
      - ./orientdb_data:/orientdb/databases
      - ./orientdb_config:/orientdb/config

volumes:
  orientdb_data:
    driver: local
  orientdb_config:
    driver: local