version: '3.8'

services:
  orientdb:
    image: orientdb:3.2.9
    container_name: dbcli
    restart: unless-stopped
    command: server.sh -Ddistributed=false -Dstorage.useWAL=false
    ports:
      - "2424:2424"
      - "2480:2480"
    environment:
      ORIENTDB_ROOT_PASSWORD: rootpwd
      ORIENTDB_USERNAME: admin
      ORIENTDB_PASSWORD: adminpwd
      ORIENTDB_DATABASE: dbcli
    volumes:
      - ./orientdb_data:/orientdb/databases
      - orientdb_config:/orientdb/config

volumes:
  orientdb_data:
    driver: local
  orientdb_config:
    driver: local